const letterPoints = [ 
    { key: 1, letter: 'a', point: 1 }, 
    { key: 2, letter: 'b', point: 4 },
    { key: 3, letter: 'c', point: 5 },
    { key: 4, letter: 'd', point: 3 },
    { key: 5, letter: 'e', point: 2 },
    { key: 6, letter: 'f', point: 5 },
    { key: 7, letter: 'g', point: 4 },
    { key: 8, letter: 'h', point: 4 },
    { key: 9, letter: 'i', point: 3 },
    { key: 10, letter: 'j', point: 7 },
    { key: 11, letter: 'k', point: 5 },
    { key: 12, letter: 'l', point: 4 },
    { key: 13, letter: 'm', point: 3 },
    { key: 14, letter: 'n', point: 3 },
    { key: 15, letter: 'o', point: 2 },
    { key: 16, letter: 'p', point: 3 },
    { key: 17, letter: 'q', point: 8 },
    { key: 18, letter: 'r', point: 3 },
    { key: 19, letter: 's', point: 3 },
    { key: 20, letter: 't', point: 3 },
    { key: 21, letter: 'u', point: 3 },
    { key: 22, letter: 'v', point: 6 },
    { key: 23, letter: 'w', point: 5 },
    { key: 24, letter: 'x', point: 6 },
    { key: 25, letter: 'y', point: 4 },
    { key: 26, letter: 'z', point: 7 },
  ];

export { letterPoints };
