

const playlistData = [
  {
    id: 1,
    title: "My Sharona",
    artist: "The Knack",
    released: "1979",
    thumb: "./logo192.png",
    position: 1,
  },
  {
    id: 2,
    title: "Don’t Stop ’til You Get Enough",
    artist: "Michael Jackson",
    released: "1979",
    thumb: require("./logo192.png"),
    position: 2,
  },
  {
    id: 3,
    title: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    released: "1970",
    thumb: require("./logo192.png"),
    position: 3,
  },
  {
    id: 4,
    title: "Go Your Own Way",
    artist: "Fleetwood Mac",
    released: "1977",
    thumb: require("./logo192.png"),
    position: 4,
  },
  {
    id: 5,
    title: "You're The One That I Want",
    artist: "Olivia Newton-John, John Travolta",
    released: "1978",
    thumb: require("./logo192.png"),
    position: 5,
  },
  {
    id: 6,
    title: "Free Bird",
    artist: "Lynyrd Skynyrd",
    released: "1973",
    thumb: require("./logo192.png"),
    position: 6,
  },
  {
    id: 7,
    title: "Dancing Queen",
    artist: "ABBA",
    released: "1976",
    thumb: require("./logo192.png"),
    position: 7,
  },
  {
    id: 8,
    title: "Your Song",
    artist: "Elton John",
    released: "1970",
    thumb: require("./logo192.png"),
    position: 8,
  },
  {
    id: 9,
    title: "O-o-h Child",
    artist: "Five Stairsteps",
    released: "1970",
    thumb: require("./logo192.png"),
    position: 9,
  },
  {
    id: 10,
    title: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    released: "1974",
    thumb: require("./logo192.png"),
    position: 10,
  },
];

export { playlistData };